steps:
  - title: "Unlock the bootloader"
    type: confirm_button
    content: "Turn on developer options and OEM Unlock on your phone."
  - title: "Boot into recovery"
    type: confirm_button
    content: "Turn on your device and wait until its fully booted."
  - title: "Boot into recovery"
    type: call_button
    content: "Reboot into bootloader"
    command: "adb reboot download"
  - title: "Boot into recovery"
    type: call_button
    content: "Flash custom recovery"
    command: "heimdall flash --no-reboot --RECOVERY recovery"
  - title: "Boot into recovery"
    type: confirm_button
    content: "Unplug the USB cable from your device. Manually reboot into recovery. Press the Volume Down + Power buttons for 8~10 seconds until the screen turns black & release the buttons immediately when it does, then boot to recovery with the device powered off, hold Volume Up + Home + Power."
  - title: "Flash LineageOS"
    type: confirm_button
    content: "Now tap 'Wipe'. Then tap 'Format Data' and continue with the formatting process. This will remove encryption and delete all files stored in the internal storage."
  - title: "Flash LineageOS"
    type: confirm_button
    content: "Return to the previous menu and tap 'Advanced Wipe', then select the 'Cache' and 'System' partitions and then 'Swipe to Wipe'."
  - title: "Flash LineageOS"
    type: confirm_button
    content: "On the device, go back and select “Advanced”, “ADB Sideload”, then swipe to begin sideload. Then confirm here"
  - title: "Flash LineageOS"
    type: call_button
    content: "Flash lineageOS image. Don't remove the USB-Cable!"
    command: "adb sideload image"
  - title: "Boot into recovery"
    type: call_button
    content: "Reboot into OS"
    command: "adb reboot"
  - title: "Successfully finished flashing"
    type: text
    content: "Have fun with LineageOS!"