name: Build release

on:
  # run once a new tag is pushed
  push:
    tags:
      - '*'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-latest']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install -r requirements.txt
    - run: python scripts/download-tools.py
    - run: black .
    - run: ruff openandroidinstaller/ --ignore E501
    - run: PYTHONPATH=openandroidinstaller:$(PYTHONPATH) pytest --cov=openandroidinstaller tests/
    
  build:
    needs: ci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install -r requirements.txt
    - run: python scripts/download-tools.py
    - run: python scripts/build.py
    - uses: actions/upload-artifact@v3
      with:
        name: openandroidinstaller-${{  github.ref_name }}-${{ matrix.os }}
        path: dist/
  
  build-windows:
    needs: ci
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install -r requirements.txt
    - run: python scripts/download-tools.py
    - run: python scripts/build.py
    - uses: actions/upload-artifact@v3
      with:
        name: openandroidinstaller-${{  github.ref_name }}-windows-latest
        path: dist/
  
  create-release:
    needs:
      - build
      - build-windows
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v3
    - name: Display structure of downloaded files
      run: ls -R
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r openandroidinstaller-${{ github.ref_name }}-macos-latest.zip openandroidinstaller-${{ github.ref_name }}-macos-latest
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r openandroidinstaller-${{ github.ref_name }}-ubuntu-20.04.zip openandroidinstaller-${{ github.ref_name }}-ubuntu-20.04
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r openandroidinstaller-${{ github.ref_name }}-ubuntu-latest.zip openandroidinstaller-${{ github.ref_name }}-ubuntu-latest
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r openandroidinstaller-${{ github.ref_name }}-windows-latest.zip openandroidinstaller-${{ github.ref_name }}-windows-latest
    - name: Display structure of downloaded files
      run: ls -R
    - name: Create release
      uses: dciborow/action-github-releases@v1.0.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        title: Release ${{ github.ref_name }}
        files: |
          openandroidinstaller-${{ github.ref_name }}-macos-latest.zip
          openandroidinstaller-${{ github.ref_name }}-ubuntu-20.04.zip
          openandroidinstaller-${{ github.ref_name }}-ubuntu-latest.zip
          openandroidinstaller-${{ github.ref_name }}-windows-latest.zip
